name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Deploy frontend to Netlify
        uses: netlify/cli@7.18.1
        with:
          args: deploy --prod --dir=frontend/build --message="Automated deployment from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: nfp_ayZDesQ4pEqnbXmGKHjBU5FxfUD66qhRc217
          NETLIFY_SITE_ID: aeda29eb-285a-493e-8bff-8a9be8cf422e

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_and_deploy_frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy backend to local server
        run: |
          cd backend
          cp -r . /home/$USERS

